apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smbgarasibmw-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/404SquadNotFound/UAS_Devops_SMB-GarasiBMW.git'
    targetRevision: develop
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
