sonar.projectKey=404SquadNotFound_UAS_Devops_SMB-GarasiBMW
sonar.organization=404squadnotfound

sonar.projectName=SMB-GarasiBMW-Fullstack
sonar.projectVersion=1.0

# Direktori source code
sonar.sources=app,database,routes,config
sonar.tests=tests

# Exclusions
sonar.exclusions=**/*.blade.php,vendor/**,storage/**,bootstrap/**,public/**,**/*.xml,**/*.json

# Test inclusions
sonar.test.inclusions=tests/**/*Test.php,tests/**/*.php

# Coverage report — path harus sesuai dengan --coverage-clover di workflow
sonar.php.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8